#!/usr/bin/env python3
"""Build the heatbox assembly guide as a self-contained HTML page, then a PDF.

Every diagram is a render of heatbox.scad and every mass is measured from the exported
STL, so the guide cannot drift from the part: regenerate the STLs and the numbers and
pictures in the PDF move with them. Nothing here is drawn or typed to look right.

    python3 make_guide.py            # writes doc/heatbox-assembly.html and .pdf

The PDF step shells out to headless Chrome, which is the only HTML-to-PDF engine on
this machine (no wkhtmltopdf, no pandoc). If Chrome is absent the HTML is still written
and the script says so rather than pretending a PDF exists.
"""
import base64
from pathlib import Path
import shutil
import subprocess
import sys

import mass

HERE = Path(__file__).resolve().parent
DOC = HERE / "doc"
OUT = HERE / "out"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

STEPS = [
    ("Print the four pieces",
     "step1",
     "One body, one deck, one lid, two caps. All five sit flat on the bed as exported "
     "and none needs support. The body is the long print; the other three are quick. "
     "Check the body's underside is a clean closed skirt before you carry on — the "
     "floor bridges across it, so a skirt that failed to stick means a sagged floor."),
    ("Drop the deck onto its ledges",
     "step2",
     "The deck falls into the box and lands on six stubs about a third of the way up. "
     "It only fits one way round: the end with the single spare hole goes to the right, "
     "away from the air inlet. Do not glue it. It lifts out for cleaning, and it is the "
     "piece you replace first if anything ever warps."),
    ("Fit the aluminium inlet tube",
     "step3",
     "Push the 20 mm bore aluminium tube through the round socket in the left-hand wall "
     "until about 25 mm stands inside the box. Three ribs inside the socket hold it; it "
     "should be a firm push, not a hammer fit. This tube exists so the hot air from your "
     "gun lands on metal instead of plastic, so never run the box without it."),
    ("Stand the two copper shoes in their pockets",
     "step4",
     "Each shoe stands upright between four corner ribs, resting on three small domes so "
     "air passes underneath. There is a finger of space at both ends of each pocket — "
     "that gap is for your tongs, so keep it clear."),
    ("Put the lid on",
     "step5",
     "The lid drops over the rim with its skirt inside the inner wall. Two rectangular "
     "slots line up over the two shoes; the two small round vents go to the right-hand "
     "end, the opposite end from the inlet."),
    ("Drop a cap over each slot",
     "step6",
     "Each cap sits on four small posts on the lid and is located by four pins. It is "
     "meant to sit slightly proud — the 2 mm gap all the way round is the chamber's "
     "exhaust, and closing it would pressurise the box. Lift a cap by its fin to take a "
     "shoe out; leave the other cap alone."),
]


def b64(path):
    return base64.b64encode(path.read_bytes()).decode()


def parts_table():
    rows = []
    for path in sorted(OUT.glob("heatbox_*.stl")):
        volume, _, box = mass.measure(path)
        grams = volume * mass.DENSITY
        copies = 2 if "_cap_" in path.name else 1
        rows.append((path.name.split("_")[1], copies, grams * copies,
                     " × ".join(f"{d:.0f}" for d in box)))
    return rows


def build_html():
    rows = parts_table()
    total = sum(r[2] for r in rows)
    body = [f"""<!-- generated by make_guide.py from heatbox.scad — do not hand-edit -->
<title>Heatbox assembly</title>
<style>
  @page {{ size: A4; margin: 16mm 14mm; }}
  :root {{ --ink:#1a1a1a; --mute:#5b6570; --line:#d8dde3; --warn:#8a2b2b;
           --warnbg:#fdf3f3; --accent:#2b4a8a; }}
  * {{ box-sizing: border-box; }}
  body {{ font: 11pt/1.5 "Inter", system-ui, sans-serif; color: var(--ink);
          margin: 0; background: #fff; }}
  h1 {{ font-size: 22pt; margin: 0 0 2mm; letter-spacing: -.01em; }}
  h2 {{ font-size: 13pt; margin: 0 0 3mm; padding-bottom: 1.5mm;
        border-bottom: 2px solid var(--accent); break-after: avoid; }}
  .sub {{ color: var(--mute); margin: 0 0 6mm; font-size: 10.5pt; }}
  .stage {{ background: var(--warnbg); border-left: 4px solid var(--warn);
            padding: 3mm 4mm; margin: 0 0 6mm; color: var(--warn); font-size: 10pt; }}
  .stage b {{ display:block; font-size: 11pt; margin-bottom: 1mm; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 10pt; margin-bottom: 5mm; }}
  th, td {{ text-align: left; padding: 1.8mm 2mm; border-bottom: 1px solid var(--line); }}
  th {{ color: var(--mute); font-weight: 600; font-size: 9pt;
        text-transform: uppercase; letter-spacing: .04em; }}
  td.n {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .two {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8mm;
          break-inside: avoid; }}
  .step {{ display: grid; grid-template-columns: 62mm 1fr; gap: 6mm;
           align-items: start; margin-bottom: 7mm; break-inside: avoid; }}
  .step img {{ width: 100%; border: 1px solid var(--line); border-radius: 2px; }}
  .step h3 {{ margin: 0 0 2mm; font-size: 12pt; }}
  .step .num {{ display: inline-block; width: 7mm; height: 7mm; line-height: 7mm;
     text-align: center; background: var(--accent); color: #fff; border-radius: 50%;
     font-size: 9.5pt; margin-right: 2mm; }}
  .step p {{ margin: 0; }}
  .how {{ display: grid; grid-template-columns: 68mm 1fr; gap: 6mm;
          align-items: start; break-inside: avoid; }}
  ol.gate {{ margin: 0 0 4mm; padding-left: 5mm; }}
  ol.gate li {{ margin-bottom: 2mm; }}
  .page {{ break-before: page; }}
  .foot {{ color: var(--mute); font-size: 8.5pt; border-top: 1px solid var(--line);
           padding-top: 2mm; margin-top: 6mm; }}
  figure {{ margin: 0; break-inside: avoid; }}
  figcaption {{ color: var(--mute); font-size: 9pt; margin-top: 1.5mm; }}
</style>

<h1>Heatbox — assembly and first run</h1>
<p class="sub">A hot-air chamber that holds two copper shoes at 110&nbsp;°C while a third
is in use. Printed in Creality Hyper&nbsp;PC.</p>

<div class="stage"><b>Read this before you build it</b>
This design has never been printed or run. Two of its inputs are assumptions, and both
change the part: the shoes are modelled 20&nbsp;×&nbsp;40&nbsp;×&nbsp;10&nbsp;mm (only
"2&nbsp;by&nbsp;4" was specified, so the 10&nbsp;mm thickness is a guess), and the heat
source is modelled as an adjustable hot-air gun set between 140 and 160&nbsp;°C.
Confirm both, regenerate, then print. The temperature gate on the last page is not
optional: Hyper&nbsp;PC is rated to about 111&nbsp;°C and this box runs at 110.</div>

<div class="two">
<div>
<h2>What you print</h2>
<table><tr><th>Piece</th><th>Qty</th><th class="n">Mass</th><th>Size mm</th></tr>"""]
    for name, copies, grams, box in rows:
        body.append(f"<tr><td>{name}</td><td>{copies}</td>"
                    f'<td class="n">{grams:.0f} g</td><td>{box}</td></tr>')
    body.append(f"""<tr><td><b>total</b></td><td></td>
      <td class="n"><b>{total:.0f} g</b></td><td></td></tr></table>
<p style="font-size:9.5pt;color:var(--mute);margin-top:-2mm">Mass is the solid volume of
each exported STL at 1.19&nbsp;g/cm³. Your slicer decides the rest.</p>
</div>
<div>
<h2>What you supply</h2>
<table>
<tr><th>Item</th><th>Why</th></tr>
<tr><td>Aluminium tube, 20&nbsp;mm bore × 1&nbsp;mm wall × 60&nbsp;mm</td>
    <td>The inlet liner. Hot air must land on metal, not on the print.</td></tr>
<tr><td>Hot-air source, adjustable 140–160&nbsp;°C, 20&nbsp;mm outlet</td>
    <td>Drives the chamber. Must sit on its own stand.</td></tr>
<tr><td>K-type thermocouple and any reader</td>
    <td>Goes in the 6.5&nbsp;mm port in the right-hand wall. This is the only proof the
        box is at temperature.</td></tr>
<tr><td>Tongs</td><td>Shoes are handled hot, never by hand.</td></tr>
</table>
</div>
</div>

<h2 style="margin-top:2mm">How it works</h2>
<div class="how">
<figure>
<img src="data:image/png;base64,{b64(DOC / 'cutaway.png')}" style="width:100%">
<figcaption>Section through the box, lid lifted off.</figcaption>
</figure>
<p style="margin:0">Hot air arrives through the aluminium tube into the plenum, the empty
space under the perforated deck. It spreads along the bottom, then rises through two rows
of 4&nbsp;mm holes flanking each shoe, so the air washes both large faces on the way up
instead of hitting one spot. It leaves through the gap under each cap and two vents at the
far end. Each shoe stands on three small domes inside corner ribs, touching the deck at as
few points as possible so air reaches underneath. The wall is two thin skins with a
5&nbsp;mm sealed air gap between them, and that trapped air is the insulation.</p>
</div>

<div class="page"></div>
<h2>Assembly</h2>
<figure style="margin-bottom:5mm">
<img src="data:image/png;base64,{b64(DOC / 'exploded.png')}"
     style="width:56mm;display:block;margin:0 auto">
<figcaption style="text-align:center">Every piece, in the order it goes together.
The grey tube and the copper shoes are not printed.</figcaption>
</figure>""")

    for index, (title, image, text) in enumerate(STEPS, start=1):
        body.append(f"""<div class="step">
  <img src="data:image/png;base64,{b64(DOC / (image + '.png'))}" alt="step {index}">
  <div><h3><span class="num">{index}</span>{title}</h3><p>{text}</p></div>
</div>""")

    body.append(f"""<div class="page"></div>
<h2>First run — do this before you trust it</h2>
<ol class="gate">
<li><b>Probe in, box empty, caps on.</b> Set the hot-air source to 140&nbsp;°C and leave
it for 30 minutes.</li>
<li><b>Read the probe.</b> Between 105 and 115&nbsp;°C is a pass. Below 105, raise the
setpoint towards 160 or increase the airflow. Above 115, lower the setpoint — do not
leave it and hope it settles, because the plastic is at its limit there.</li>
<li><b>Look at the deck.</b> It is the hottest printed piece and the cheapest to replace,
so it is the part that tells you first if the box is too hot. Any softening or sag means
stop.</li>
<li><b>Time a real recovery, once for each pocket.</b> Take a shoe out, let it cool by
about 40&nbsp;°C, put it back, and count the minutes until the probe returns to
105&nbsp;°C. Do this for the left pocket and the right pocket separately: the left one
sits over the end of the inlet tube and the probe is in the right-hand wall, so the two
do not behave the same. The slower of the two is your swap interval — write it on the
box.</li>
</ol>

<h2>In use</h2>
<p>One shoe out, two resting. Lift one cap, take that shoe with tongs, put the returning
shoe into the empty pocket, drop the cap back over the pins. The other cap stays shut.
Expect a returned shoe to need somewhere between 6 and 17 minutes to come back to
temperature — that range is genuine uncertainty about how well the jets reach the shoe
faces, which is exactly what step 4 of the first run measures and settles.</p>

<h2>Limits — the three ways this breaks</h2>
<table>
<tr><th>Do not</th><th>Because</th></tr>
<tr><td>Rest the weight of the hot-air gun on the inlet socket</td>
    <td>Polycarbonate at 110&nbsp;°C creeps under steady load. Give the gun its own
        stand. The socket locates the tube, it does not carry anything.</td></tr>
<tr><td>Run it without the aluminium tube</td>
    <td>Air leaving the source is hotter than the chamber, and it would land straight on
        plastic that is already at its rated limit.</td></tr>
<tr><td>Seal, tape or weigh down the caps</td>
    <td>The gap under each cap is the exhaust. Closing it pressurises the box and pushes
        hot air out through every printed seam.</td></tr>
</table>

<h2>Printing</h2>
<p>Creality Hyper&nbsp;PC, nozzle 240–260&nbsp;°C, bed 50–80&nbsp;°C, chamber heat on,
filament dried first. The model is built around a 0.8&nbsp;mm nozzle at 0.82&nbsp;mm line
width and 0.4&nbsp;mm layers: every wall is exactly two extrusion lines thick and every
plate a whole number of layers, so the slicer has no leftover slivers to fill. Changing
nozzle or layer height means regenerating the STLs with the new numbers, not just
re-slicing — the model refuses to build if the walls no longer divide evenly.</p>

<div class="foot">Generated from heatbox.scad by make_guide.py. Diagrams are renders of
the same file the STLs come from. Design not yet printed or measured on hardware.</div>""")
    return "\n".join(body)


def main():
    DOC.mkdir(exist_ok=True)
    missing = [n for n in ["exploded", "cutaway"] + [s[1] for s in STEPS]
               if not (DOC / f"{n}.png").is_file()]
    if missing:
        print(f"missing renders: {missing}\n"
              "run the render loop in README.md first", file=sys.stderr)
        return 2
    if not list(OUT.glob("heatbox_*.stl")):
        print("no STLs in out/ — nothing to measure", file=sys.stderr)
        return 2

    html_path = DOC / "heatbox-assembly.html"
    html_path.write_text(build_html())
    print(f"wrote {html_path.relative_to(HERE)} ({html_path.stat().st_size/1024:.0f} KB)")

    if not Path(CHROME).exists() and shutil.which("google-chrome") is None:
        print("Chrome not found — HTML written, PDF NOT generated.", file=sys.stderr)
        return 1
    pdf_path = DOC / "heatbox-assembly.pdf"
    proc = subprocess.run(
        [CHROME, "--headless", "--disable-gpu", "--no-pdf-header-footer",
         f"--print-to-pdf={pdf_path}", html_path.as_uri()],
        capture_output=True, text=True, timeout=180)
    if not pdf_path.is_file() or pdf_path.stat().st_size < 20000:
        print("PDF missing or suspiciously small:\n" + proc.stderr[-800:], file=sys.stderr)
        return 1
    print(f"wrote {pdf_path.relative_to(HERE)} "
          f"({pdf_path.stat().st_size/1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
